### ISSUE TITLE
Jerma Daily Routine.

### ISSUE THREAD

**Issue by phaenixC** [JermaSites/JermaDebt#40]
The specific request of the Daily Routine was to "tell his daily routine *to prove he was not a (paraphrasing) psycho killer" this clearly goes beyond simply asking for the debt to be removed, and requires he PROVE he is NOT A KILLER.

While I personally believe Jerma to not be a killer, the daily routine provided had sufficient gaps within it to leave time for killing. A link or archive of any polls on the decision of the validity of the Daily Routine is also not provided.

My suggestion for a course of action is to either 1. Give back the debt until jerma can *PROVE* (in the eyes of a "burden of evidence falls on the accused" legal system, perhaps or perhaps not performed live as a trial of Jerma.) he is not a killer, or 2. Provide a citation for the agreement of the majority of chat (who are educated on and have watched the full clip from start to finish with no cuts ((this can be provided if you give me time to find it))) on the validity of the removal of that portion of the debt.

Thank you for your time.

**Comment by s-crypt** [comment]
While I personally agree with your suggestion and viewpoint, however my only goal is to please chat, the rulemakers of this game. They were satisfied with his explanation (despite the pitiful one it was) and settled to take off the debt. If I go against chat, then my purpose to be the reliable, official, and trustworthy ledger of this e-Clown's debt has failed. I appreciate your concern with the matter, but this would have to be an issue that the majority of chat would have to agree on.

also he prob gonna quintuple his debt soon because hes bad at this whole gambling thing lol

**Comment by phaenixC** [comment]
Agreed. I would never ask you to go against chat directly. I suppose I could file a M.E.M.E file with the Reddit division of the Coordinated Humans Action Team. If sufficient upheaval is raised it may reach the upper echelons of CHAT. Of course, that's only an idea though. Unless Anything comes of this, I believe this is satisfactory enough to close the issue.
